### ISSUE TITLE
[KPI-4] NoClassDefFoundError

### ISSUE THREAD

**Issue by Kev575** [Kev575/KevsPermissions#5]
"[10:13:09 ERROR]: Could not load 'plugins\KevsPermissionsGUI-1_2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: kev575/permissions/modules/KevsPermsAddon
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: kev575/permissions/modules/KevsPermsAddon
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_91]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_91]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_91]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_91]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_91]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: kev575.permissions.modules.KevsPermsAddon
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_91]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_91]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_91]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_91]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_91]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        ... 6 more"

**Comment by Kev575** [comment]
Fixed in KPGUI-1.3.
Removed Addon Support and let them run as own plugin.
